### ISSUE TITLE
chaosblade-operator1.7.2 pod cpu故障注入失败

### ISSUE THREAD

**Issue by wjsshide** [chaosblade-io/chaosblade-operator#234]
**描述：** operator1.7.2注入pod的cpu故障的时候， 直接会把该pod下的容器cpu直接打满
debug发现获取runtime.NumCpu()获取的是宿主机的核数不是容器的cpu核数

**yaml文件：**
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: cpu-pod-6
spec:
  experiments:
  - scope: pod
    target: cpu
    action: fullload
    desc: "increase pod cpu load by names"
    matchers:
    - name: names
      value:
      - "nginx-6664874ddd-gqjhx"
    - name: cpu-percent
      value:
      - "60"
    - name: namespace
      value:
      - "nginx"
    - name: timeout
      value:
      - "60"

**Comment by binbin0325** [comment]
pod 注入cpu负载本质就是对容器注入cpu负载，这没啥问题。

**Comment by wjsshide** [comment]
> pod 注入cpu负载本质就是对容器注入cpu负载，这没啥问题。 runtime.NumCpu()获取的是当前容器的cpu核心数，这里通过_ "go.uber.org/automaxprocs/maxprocs" 进行控制了

您好  我对pod注入cpu故障， cpu-percent是60%， pod的cpu limit是1000m， 正常来说 应该把容器cpu打满60%， 但是事实上打了100%， 我加log的 时候发现untime.NumCpu()获取的宿主机的核数，不是容器的核数，go.uber.org/automaxprocs/maxprocs 没生效


我把uber的方法显示在代码调用了一下，结果发现报错了，我理解是因为这个报错导致的cpu获取有问题， 报错信息如下
msg="failed to set GOMAXPROCS: path \"/kubepods.slice/kubepods-pod3f8b57a9_829a_4d47_b220_b830da173956.slice/cri-containerd-2b7a54862ac13ec3bf45d691f6e900ba67b27ca3718dab124f6d04e1644ee53e.scope\" is not a descendant of mount point root \"/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod497e810a_3a2e_49d6_a6a3_ca9b49062993.slice/cri-containerd-f3ee784b971d2e8e2bff1714496b5c813a9f6dc0e726530b004a4a1a01bc470e.scope\" and cannot be exposed from \"/sys/fs/cgroup/systemd\"" location="/go/src/github.com/chaosblade-io/chaosblade/target/cache/chaosblade-exec-os/exec/cpu/cpu.go:180" uid=1c50e84360e9a90c

**Comment by spencercjh** [comment]
我也发现了同样的问题。

**Comment by spencercjh** [comment]
> pod 注入cpu负载本质就是对容器注入cpu负载，这没啥问题。 runtime.NumCpu()获取的是当前容器的cpu核心数，这里通过_ "go.uber.org/automaxprocs/maxprocs" 进行控制了

并不正确，automaxprocs/maxprocs 获取的是 daemonset pod 的 CPU 数量，详情可以看这个 issue：https://github.com/chaosblade-io/chaosblade/issues/1079

**Comment by spencercjh** [comment]
This issue WAS RESOLVED by https://github.com/chaosblade-io/chaosblade-exec-os/pull/177

**Comment by flyingbutter** [comment]
> This issue WAS RESOLVED by [chaosblade-io/chaosblade-exec-os#177](https://github.com/chaosblade-io/chaosblade-exec-os/pull/177)

I build the operator with latest commit in chaosblade-exec-os but the issue still persists, no matter what percentage i give it still uses 100% of cpu

**Comment by spencercjh** [comment]
> > This issue WAS RESOLVED by [chaosblade-io/chaosblade-exec-os#177](https://github.com/chaosblade-io/chaosblade-exec-os/pull/177)
> 
> I build the operator with latest commit in chaosblade-exec-os but the issue still persists, no matter what percentage i give it still uses 100% of cpu

You have to build chaosblade and redeploy the daemonset chaosblade-tool with the new image... In this case, the operator is not main issue.

**Comment by flyingbutter** [comment]
> > > This issue WAS RESOLVED by [chaosblade-io/chaosblade-exec-os#177](https://github.com/chaosblade-io/chaosblade-exec-os/pull/177)
> > 
> > 
> > I build the operator with latest commit in chaosblade-exec-os but the issue still persists, no matter what percentage i give it still uses 100% of CPU
> 
> I'm sorry for not getting back to you sooner.
> 
> You have to build chaosblade and redeploy the daemonset chaosblade-tool with the new image... In this case, the operator is not the main trouble leading the bug because code in `chaosblade-exec-os` is finally executed by chaosblade CLI. And in K8s runtime, the CLI is distributed through the daemonset chaosblade-tool.

I thought it was the operator , sorry for the confusion, I ll try that

**Comment by acuicui1128** [comment]
> > > 该问题已由[chaosblade-io/chaosblade-exec-os#177解决](https://github.com/chaosblade-io/chaosblade-exec-os/pull/177)
> > 
> > 
> > 我使用 chaosblade-exec-os 中的最新提交构建了操作员，但问题仍然存在，无论我给出多少百分比，它仍然使用 100％ 的 CPU
> 
> 很抱歉没有早点回复您。
> 
> 您必须构建 Chaosblade，并使用新镜像重新部署守护进程集 Chaosblade-tool……在这种情况下，操作员并非导致错误的主要问题，因为代码`chaosblade-exec-os`最终由 Chaosblade CLI 执行。并且在 K8s 运行时中，CLI 是通过守护进程集 Chaosblade-tool 分发的。



> > > This issue WAS RESOLVED by [chaosblade-io/chaosblade-exec-os#177](https://github.com/chaosblade-io/chaosblade-exec-os/pull/177)
> > 
> > 
> > I build the operator with latest commit in chaosblade-exec-os but the issue still persists, no matter what percentage i give it still uses 100% of CPU
> 
> I'm sorry for not getting back to you sooner.
> 
> You have to build chaosblade and redeploy the daemonset chaosblade-tool with the new image... In this case, the operator is not the main trouble leading the bug because code in `chaosblade-exec-os` is finally executed by chaosblade CLI. And in K8s runtime, the CLI is distributed through the daemonset chaosblade-tool.

你好，我在尝试在本机模拟k8s集群，搭建一下chaosblade-operator，想用1.7.4版本的，使用命令是：
helm install chaosblade charts/chaosblade-operator-1.7.4.tgz \
  --namespace chaosblade \
  --set operator.image.tag=1.7.4 \
  --set blade.image.tag=1.7.4 \
  --set plugins.jvm.enabled=true \
  --set plugins.go.enabled=true
我看这个问题的修改代码是在chaosblade-exec-os项目的master分支，不在1.7.4里。chaosblade-tool的最新tag也是1.7.4。这是不是意思是修复的代码只在chaosblade-exec-os的master上，我这种方式部署并不会拉到这个修复改动？？请教一下怎么部署呢？我是本机mac m4安装了一个OrbStack来模拟k8s环境。
正在学习k8s集群上部署chaosblade-operator+chaosblade-tool+jvm+go(好像还不支持)。期待您的回复和指导，感恩的心~~~
